### ISSUE TITLE
Error Loading Plugin

### ISSUE THREAD

**Issue by jamesoz10** [anthonywebb/homebridge-cbus#26] opened 2017-03-02 01:35 UTC
Hi Anthony,

I'm new to Homebridge/cbus and keen to get it working for my cbus install at home. Very pleased to find a control solution for my cbus.

I've managed to get Homebridge working and started to control my wemo switches. But not having any luck with getting the cbus plugin working. It's probably just my config.

[3/2/2017, 1:05:43 AM] ====================
[3/2/2017, 1:05:44 AM] ERROR LOADING PLUGIN homebridge-cbus:
[3/2/2017, 1:05:44 AM] SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-cbus/lib/cgate-client.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I'm trying to connect to a remote laptop with toolkit running connected via usb to a PAC. I've updated the access text file with the homebridge server ip address.

Any ideas on what I'm doing wrong?

file:///home/pi/.homebridge/config.json

**Comment by simonhac** [comment] 2017-03-02 01:49
@jamesoz10 simon here. try pasting your `config.json` file into [jsonlint.com](http://jsonlint.com/).

if the problem isn't obvious from the result, please post your `config.json` file into this ticket.

**Comment by anthonywebb** [comment] 2017-03-02 01:50
Yea, looks to me like maybe you have an equal sign in your JSON instead of
a colon?

**Comment by jamesoz10** [comment] 2017-03-02 01:55
I'm just using the sample config.json, but changed some details.

**Comment by jamesoz10** [comment] 2017-03-02 01:57
[config.json.txt](https://github.com/anthonywebb/homebridge-cbus/files/812567/config.json.txt)

**Comment by anthonywebb** [comment] 2017-03-02 02:01
Maybe could try to use the platform_export variable empty?  That is
relatively new and might be the cause?  JSON file looks solid to me.

**Comment by jamesoz10** [comment] 2017-03-02 02:06
Hi,

Just tried that, but same error, I'm afraid.

James

**Comment by anthonywebb** [comment] 2017-03-02 02:15
In cbus-utils.js, line 40 there is a "max = 100" not entirely sure if that
is valid syntax or not.  I've never done it that way before.  Simon, could
that be problematic?  The error trace looks like cgate-client line 14
(which iincludes cbus-utils) is the culprit, so I am hunting around there.

**Comment by simonhac** [comment] 2017-03-02 02:34
@anthonywebb yes, i understand that to be valid ES6 syntax.

could it be that @jamesoz10 is not using a recent version of `nodejs`?

**Comment by anthonywebb** [comment] 2017-03-02 02:43
@jamesoz10 try "node --version" lets see what version you have?

**Comment by jamesoz10** [comment] 2017-03-02 04:33
v4.3.2

**Comment by anthonywebb** [comment] 2017-03-02 04:40
That is definitely the problem.  Go ahead and install the latest version of
nodejs.

**Comment by jamesoz10** [comment] 2017-03-02 09:46
Thanks for the help. Still no luck.

I've upgraded nodejs I believe.


pi@raspberrypi:~ $ sudo apt install nodejs
Reading package lists... Done
Building dependency tree
Reading state information... Done
nodejs is already the newest version.
The following packages were automatically installed and are no longer
required:
  libasn1-8-heimdal libc-ares2 libcwiid1 libgssapi3-heimdal
  libhcrypto4-heimdal libheimbase1-heimdal libheimntlm0-heimdal
  libhx509-5-heimdal libjs-prettify libkrb5-26-heimdal libllvm3.7
  libqscintilla2-11 libqscintilla2-l10n libqt4-network libqt4-xmlpatterns
  libqtwebkit4 libroken18-heimdal libruby1.9.1 libruby1.9.1-dbg libtcl8.5
  libtcltk-ruby1.9.1 libtk8.5 libv8-3.14.5 libwind0-heimdal libxfce4ui-1-0
  pypy-upstream-doc ri1.9.1 ruby1.9.1 ruby1.9.1-dev ruby1.9.1-examples
  ruby1.9.1-full ruby1.9.3 supercollider supercollider-common
  supercollider-ide supercollider-language supercollider-supernova tcl8.5
  tk8.5 wiringpi xfce-keyboard-shortcuts
Use 'apt-get autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
pi@raspberrypi:~ $ node -v
v4.3.2
pi@raspberrypi:~ $ apt list nodejs -a
Listing... Done
nodejs/unknown,now 7.6.0-1nodesource1~jessie1 armhf [installed]
nodejs/stable 0.10.29~dfsg-2 armhf

pi@raspberrypi:~ $ nodejs -v
v7.6.0

But, still errors when running Homebridge

pi@raspberrypi:~ $ homebridge
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility
layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <
http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is
not supported (or only supported partially) in the Apple Bonjour
compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <
http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
[3/2/2017, 9:39:25 AM] ====================
[3/2/2017, 9:39:25 AM] ERROR LOADING PLUGIN homebridge-cbus:
[3/2/2017, 9:39:25 AM] SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous>
(/usr/local/lib/node_modules/homebridge-cbus/lib/cgate-client.js:14:19)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
[3/2/2017, 9:39:25 AM] ====================
[3/2/2017, 9:39:25 AM] Loaded plugin: homebridge-gpio
[3/2/2017, 9:39:25 AM] Registering accessory 'homebridge-gpio.GPIO'
[3/2/2017, 9:39:25 AM] ---
[3/2/2017, 9:39:25 AM] Loaded plugin: homebridge-gpio-relay
[3/2/2017, 9:39:25 AM] Registering accessory 'homebridge-gpio-relay.relay'
[3/2/2017, 9:39:25 AM] ---
[3/2/2017, 9:39:25 AM] Loaded plugin: homebridge-gpio-shutter
[3/2/2017, 9:39:25 AM] Registering accessory
'homebridge-gpio-shutter.shutter'
[3/2/2017, 9:39:25 AM] ---
[3/2/2017, 9:39:25 AM] Loaded plugin: homebridge-harmonyhub
[3/2/2017, 9:39:27 AM] Registering platform
'homebridge-harmonyhub.HarmonyHub'
[3/2/2017, 9:39:27 AM] ---
[3/2/2017, 9:39:27 AM] Loaded plugin: homebridge-http
[3/2/2017, 9:39:27 AM] Registering accessory 'homebridge-http.Http'
[3/2/2017, 9:39:27 AM] ---
[3/2/2017, 9:39:27 AM] Loaded plugin: homebridge-panasonictv
[3/2/2017, 9:39:27 AM] Registering accessory 'homebridge-panasonictv.TV'
[3/2/2017, 9:39:27 AM] ---
[3/2/2017, 9:39:27 AM] Loaded plugin: homebridge-people
[3/2/2017, 9:39:27 AM] Registering accessory 'homebridge-people.people'
[3/2/2017, 9:39:27 AM] ---
[3/2/2017, 9:39:28 AM] Loaded plugin: homebridge-platform-wemo
[3/2/2017, 9:39:28 AM] Registering platform
'homebridge-platform-wemo.BelkinWeMo'
[3/2/2017, 9:39:28 AM] ---
[3/2/2017, 9:39:28 AM] Loaded plugin: homebridge-rcswitch-gpiomem
[3/2/2017, 9:39:28 AM] Registering accessory
'homebridge-rcswitch-gpiomem.RcSwitch'
[3/2/2017, 9:39:28 AM] ---
[3/2/2017, 9:39:28 AM] Loaded plugin: homebridge-suncalc
[3/2/2017, 9:39:28 AM] Registering accessory 'homebridge-suncalc.Suncalc'
[3/2/2017, 9:39:28 AM] ---
[3/2/2017, 9:39:28 AM] Loaded plugin: homebridge-telldus
[3/2/2017, 9:39:28 AM] Registering platform 'homebridge-telldus.Telldus'
[3/2/2017, 9:39:28 AM] ---
[3/2/2017, 9:39:29 AM] Loaded plugin: homebridge-wemo
[3/2/2017, 9:39:29 AM] Registering accessory 'homebridge-wemo.WeMo'
[3/2/2017, 9:39:29 AM] ---
[3/2/2017, 9:39:30 AM] Loaded plugin: homebridge-wol
[3/2/2017, 9:39:30 AM] Registering accessory 'homebridge-wol.Computer'
[3/2/2017, 9:39:30 AM] ---
[3/2/2017, 9:39:30 AM] Loaded config.json with 0 accessories and 1
platforms.
[3/2/2017, 9:39:30 AM] ---
[3/2/2017, 9:39:30 AM] Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:124
      throw new Error("The requested platform '" + name + "' was not
registered by any plugin.");
      ^

Error: The requested platform 'homebridge-cbus.CBus' was not registered by
any plugin.
    at API.platform
(/usr/local/lib/node_modules/homebridge/lib/api.js:124:13)
    at Server._loadPlatforms
(/usr/local/lib/node_modules/homebridge/lib/server.js:284:45)
    at Server.run
(/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports
(/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous>
(/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3

Sorry, new to Nodejs, is there something else I need to do?

**Comment by simonhac** [comment] 2017-03-02 11:55
@anthonywebb fyi, default parameters were introduced in ES6:
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Functions/default_parameters

support for default parameters looks to be definitely in nodejs v7.6.0 -- see [node.green](http://node.green).

i haven't had the opportunity to play with raspberry pi yet -- there's nothing weird about the version of V8 used by nodejs on pi is there?

**Comment by simonhac** [comment] 2017-03-02 12:01
@jamesoz10 please enter the following into your terminal:
`node -p process.versions.v8`

that'll tell us which version of the v8 runtime your node has embedded.

**Comment by jamesoz10** [comment] 2017-03-02 12:24
Thanks Simon,

that gives me:

4.5.103.35

**Comment by simonhac** [comment] 2017-03-02 12:55
v8 version 4.5.103 doesn't support default functions. (found by [backtracking](https://bytearcher.com/articles/how-to-check-if-node-implements-es6-language-feature/) issue 2160 [here](https://github.com/v8/v8/blob/4.5.103/test/test262-es6/test262-es6.status))

node version 7.6.0 should be linked against v5.5.372.40 (according to [this page](https://nodejs.org/en/download/releases/)).

i'm sorry @jamesoz10 i don't know enough about node to say why you are running an unexpected version of v8. (perhaps homebridge is starting up against an old version of node? i don't really know what i'm talking about. i'm a relative noob myself.)

**Comment by simonhac** [comment] 2017-03-02 21:21
@jamesoz10 as i mentioned, i'm a node noob, so you will likely get better help elsewhere, but this is what i'd do:

find the path to homebridge -- on my mac it is `/usr/local/lib/node_modules/homebridge/bin/homebridge`. it is just a js file that node executes. open it up and insert the lines:
```javascript
var util = require('util');
console.log(util.inspect(process.versions));
```
after `'use strict';`. eg. the file should look like this:

```javascript
#!/usr/bin/env node

//
// This executable sets up the environment and runs the HomeBridge CLI.
//

'use strict';

var util = require('util');
console.log(util.inspect(process.versions));

process.title = 'homebridge';

// Find the HomeBridge lib
var path = require('path');
var fs = require('fs');
var lib = path.join(path.dirname(fs.realpathSync(__filename)), '../lib');

// Run HomeBridge
require(lib + '/cli')();
```

now start homebridge. i get the following:
```
{ http_parser: '2.7.0',
  node: '6.9.1',
  v8: '5.1.281.84',
  uv: '1.9.1',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '57.1',
  modules: '48',
  openssl: '1.0.2j' }
[3/3/2017, 8:14:56 AM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-cbus' since we already loaded the same plugin from '/Users/simon/dev/homebridge-cbus'.
[3/3/2017, 8:14:56 AM] Loaded plugin: homebridge-cbus
[3/3/2017, 8:14:56 AM] Registering platform 'homebridge-cbus.CBus'
...
```

given that there's something fishy going on, the above will let us know exactly what version of node and v8 your homebridge is running against.

**Comment by jamesoz10** [comment] 2017-03-02 23:18
Thanks Simon,

That gives me:

pi@raspberrypi:~ $ homebridge
{ http_parser: '2.5.2',
  node: '4.3.2',
  v8: '4.5.103.35',
  uv: '1.8.0',
  zlib: '1.2.8',
  ares: '1.10.1-DEV',
  icu: '56.1',
  modules: '46',
  openssl: '1.0.2g' }

So looks like node is not upgrading properly.

I'll keep trying!

**Comment by simonhac** [comment] 2017-03-02 23:25
@jamesoz10. yuck, that version of node is 12+ months old, and there's been a lot of development since then.

i'm sorry i don't know enough about raspberry pi to help you sort out the path issues. good luck!

**Comment by jamesoz10** [comment] 2017-03-03 02:15
Thanks for the tips.

I just started from scratch and now have it loading up correctly and the
latest version of nodejs.

Although now I can't connect to my c-gate. Which is running on a windows pc
connected via usb to my cbus PAC.

I have toolkit open, and can connect to the network in that. Have also
entered the Pi's IP in the access file.

I'm guessing I'm missing something here.

[3/3/2017, 2:09:44 AM] [CBus] Initializing homebridge-cbus.CBus platform...
  cbus:platform Connecting to the local C-Gate server… +0ms
[3/3/2017, 2:09:44 AM] Loading 0 accessories...
  cbus:client C-Gate socket error: Error: connect ETIMEDOUT
192.168.0.95:20023 +2m
  cbus:client C-Gate socket closed +7ms

**Comment by simonhac** [comment] 2017-03-03 03:10
see if you can telnet to port 20023 of your windows machine. for me it looks like this:

```
$ telnet 10.0.1.22 20023
Trying 10.0.1.22...
Connected to localhost.
Escape character is '^]'.
201 Service ready: Clipsal C-Gate Version: v2.10.6 (build 3145) #cmd-syntax=1.0
```

(later, i'd recommend that you move C-Gate to your Pi.)

**Comment by jamesoz10** [comment] 2017-03-04 12:10
Great stuff, thanks for all the help. I've managed to get it all working
now. Downloaded the unified list and copied it across to my config.json and
made a few changes. All picked up in Homekit.

I have full siri control now. Awesome!

Cheers James

**Comment by anthonywebb** [comment] 2017-03-04 14:43
Good stuff, congrats!

**Comment by simonhac** [comment] 2017-03-05 10:33
good work @jamesoz10 -- i'll close this issue now.

**Closed by simonhac** 2017-03-05 10:33 UTC
