### ISSUE TITLE
Capturing changes on a remote network?

### ISSUE THREAD

**Issue by greiginsydney** [anthonywebb/homebridge-cbus#45] opened 2017-04-18 08:55 UTC
Hey Guys,

Is there a trick to getting homebridge to correctly capture activity on a remote network?

I have two networks here at home (254 and 253) separated by a Bridge.

I'm normally resident on 254 and I can initiate changes into dimmers on 253 AOK from local switches + Homebridge, but if a change is made to a group *on* 253 from a switch on 254, or by a switch on 253 to 253, it's not reflected in HomeBridge/Home - and thus the two fall out of sync.

If I monitor the network (Telnet:C-gate 20025) I'm seeing the changes being reflected back into 254 from 253 (as per the Bridge setting of "Send to adjacent network"):

Greig turns light 253/16 on / off from its switch in network 253:
```
lighting ramp //19P/253/56/16 153 0 #sourceunit=65 OID=fe65e5c0-063c-1035-b3dc-f0ba9991de2c
lighting ramp //19P/254/56/16 153 0 #sourceunit=-1 OID=186be5b0-0641-1035-b498-f0ba9991de2c
lighting off //19P/253/56/16  #sourceunit=65 OID=fe65e5c0-063c-1035-b3dc-f0ba9991de2c
lighting off //19P/254/56/16  #sourceunit=-1 OID=186be5b0-0641-1035-b498-f0ba9991de2c
```

(Source unit 65 is the address of the KEY2 unit in the bathroom on network 253, controlling the dimmer on 253/56/16).

I have my Groups all duplicated between networks (which I believe to be the correct config) and config.json edited to reflect to network 253 for the units on the remote network:

` { "type": "dimmer", "id": 16, "network": "253", "name": "B1 LX", "enabled": true },`

I've also tried deleting Group 16 from 254 without success.

Any ideas?

**Comment by simonhac** [comment] 2017-04-20 04:32
@greiginsydney i might be able to help, but firstly:
* can you please capture the log from `homebridge-cbus` for this transaction?
* i'm not sure why you'd need to duplicate the groups between the networks -- is that intended to be a cgate or homebridge workaround?
* sorry, but what is `HomeBridge/Home`?

**Comment by greiginsydney** [comment] 2017-04-20 12:40
Hi @simonhac.

OK, this is awkward. Now I've gotten Homebridge to run in the Pi (like a Service?) I now don't know how to 'break' it so I can run it manually and capture logs! If I sign into the Pi now as the same homebridge user account (the same one it's already running as the service) it spits a (valid) error because the port's already in use. Leave that one with me and I'll see if I can do it more elegantly than disabling the auto-start and rebooting...


Duplicating groups between networks is as I understand it how one's meant to interface between devices/Groups on separate networks. (This installation has been working AOK for some years in that config, but I'd admit that doesn't necessarily make it best practice / supported). Having said that however, in [this Clipsal training video](https://youtu.be/en3pcE-TraY) they demonstrate (at around 6:00) copying a group between networks so that you can control across the bridge.


By Homebridge/Home I meant the Home app on my iPhone, talking to Homebridge the 'accessory'.

-G.

**Comment by greiginsydney** [comment] 2017-04-21 23:46
Hi @simonhac , I got there. "ps aux" can ID the process # that my background user is running Homebridge as, and kill zaps it so I can then run it manually.

This seems to be the relevant line from the output:
`  cbus:client rx event { time: '20170421-233131', code: 730, processed: true, netId: //19P/253/56/16, level: 0, sourceunit: 65, ramptime: 0, type: 'event', raw: '#e# 20170421-233131 730 //19P/253/56/16 fe65e5c0-063c-1035-b3dc-f0ba9991de2c new level=0 sourceunit=65 ramptime=0' } +3s
  cbus:client rx unparsable line: '#e# 20170421-233131 730 //19P/253/56/16 fe65e5c0-063c-1035-b3dc-f0ba9991de2c new level=0 sourceunit=65 ramptime=0', error: AssertionError: getGroupName can only search in default network
`
This is in response from Group 16 on network 253 being turned on by its local switch within that same network.

That is then followed by:
`  cbus:client rx event { time: '20170421-233131', code: 730, processed: true, netId: //19P/254/56/16, level: 0, sourceunit: -1, ramptime: 0, type: 'event', raw: '#e# 20170421-233131 730 //19P/254/56/16 186be5b0-0641-1035-b498-f0ba9991de2c new level=0 sourceunit=-1 ramptime=0' } +7ms
  cbus:client rx unparsable line: '#e# 20170421-233131 730 //19P/254/56/16 186be5b0-0641-1035-b498-f0ba9991de2c new level=0 sourceunit=-1 ramptime=0', error: TypeError: Cannot read property 'tag' of undefined
`
(My tags file defines Unit 16 in both networks 253 & 254 BTW).

The end result is that I can CONTROL the lights on this remote network from Homebridge, but Homebridge doesn't accept state changes that originate from network 253, and thus Homebridge falls out of sync with reality.

**Comment by simonhac** [comment] 2017-04-22 00:48
@greiginsydney ok, i know the piece of code responsible for this -- thanks for your legwork.
it shouldn't be too hard to fix, but testing it will be imperfect as i don't have two bridged networks.

it would help if i had a copy of your project file -- i'll leave my email address as a comment on your greiginsydney.com site.

**Comment by simonhac** [comment] 2017-04-25 23:13
@greiginsydney i'm taking a look at this code as i work on #33.

i think i have my head around bridged networks -- it's all a bit abstract for me as i have only a single network. i take it that you have your bridge configured to forward all messages between the adjacent networks. i can now understand why it is recommended to copy groups between networks in this configuration -- any message sent to group `//PROJECT/254/x/y` will also be sent to  `//PROJECT/253/x/y`, so the duplication is a workaround for the collapsing of the address space.

working on it…

**Comment by simonhac** [comment] 2017-05-01 07:36
@greiginsydney this has now been merged (PR #47). please update and test when you get a chance. if it works, please close this issue.

**Comment by greiginsydney** [comment] 2017-05-01 09:00
Sorry guys, no dice: it's broken badly now. I can still make changes from my iPhone but now not even a change on the LOCAL network is being read correctly:

` cbus:client rx unparsable line: '#e# 20170501-085740 730 //19P/254/56/35 1c6943e0-107a-1035-b74b-8a12e8e62b35 new level=204 sourceunit=54 ramptime=0', error: Error: database access before initialisation
  cbus:client     at CGateDatabase.getNetworkEntity (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:344:9)
  cbus:client     at CGateDatabase.getTag (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:330:21)
  cbus:client     at CBusPlatform._processEvent (/usr/lib/node_modules/homebridge-cbus/index.js:105:45)
  cbus:client     at CBusPlatform.<anonymous> (/usr/lib/node_modules/homebridge-cbus/index.js:147:8)
  cbus:client     at emitOne (events.js:96:13)
  cbus:client     at CBusClient.emit (events.js:191:7)
  cbus:client     at CBusClient._socketReceivedLine (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:634:10)
  cbus:client     at Carrier.<anonymous> (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:175:9)
  cbus:client     at emitOne (events.js:96:13)
  cbus:client     at Carrier.emit (events.js:191:7) +5ms
  cbus:client rx event { time: '20170501-085740', code: 730, processed: true, netId: //19P/253/56/35, level: 80, sourceunit: -1, ramptime: 0, type: 'event', raw: '#e# 20170501-085740 730 //19P/253/56/35 - new level=204 sourceunit=-1 ramptime=0' } +5ms
  cbus:client rx unparsable line: '#e# 20170501-085740 730 //19P/253/56/35 - new level=204 sourceunit=-1 ramptime=0', error: Error: database access before initialisation
  cbus:client     at CGateDatabase.getNetworkEntity (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:344:9)
  cbus:client     at CGateDatabase.getTag (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:330:21)
  cbus:client     at CBusPlatform._processEvent (/usr/lib/node_modules/homebridge-cbus/index.js:105:45)
  cbus:client     at CBusPlatform.<anonymous> (/usr/lib/node_modules/homebridge-cbus/index.js:147:8)
  cbus:client     at emitOne (events.js:96:13)
  cbus:client     at CBusClient.emit (events.js:191:7)
  cbus:client     at CBusClient._socketReceivedLine (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:634:10)
  cbus:client     at Carrier.<anonymous> (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:175:9)
  cbus:client     at emitOne (events.js:96:13)
  cbus:client     at Carrier.emit (events.js:191:7) +2ms
`

Is that enough of a snippet? Let me know if you want to see any more logs/details.

**Comment by simonhac** [comment] 2017-05-01 10:15
@greiginsydney bugger, that means that the C-Gate  database parser failed to decode the response from `DBGETXML`.

there should be a line earlier in the console log along the lines of:
````
ERROR failed to load C-Gate database: <some error with stack trace>
````

can you please look for that and post it?


(best to use the ![image](https://cloud.githubusercontent.com/assets/20500649/25577589/88c5c502-2eaa-11e7-95e9-0f8d8859bf27.png) button to quote console text.)

**Comment by greiginsydney** [comment] 2017-05-01 10:57
Hi @simonhac , is this what you're looking for?

`  cbus:client sent command '[100] dbgetxml //19P' +307ms
[5/1/2017, 10:29:58 AM] Homebridge is running on port 51826. 
cbus:client rx response { commandId: 100, code: 400, matched: false, processed: false, type: 'response', raw: '[100] 400 Syntax Error.' } +67ms 
cbus:client matched request '[100] dbgetxml //19P' with response '[100] 400 Syntax Error.' (0 pending requests) +8ms 
cbus:client rx unparsable line: '[100] 400 Syntax Error.', error: TypeError: Cannot read property 'content' of undefined`

If so, my friend the Syntax error and I go way back. From my original testing of my C-Bus PHP interface, I found the first otherwise valid command issued to the Bus after connection ALWAYS responded with a 400. I took to sending a NOOP (or at least a CR) as my first command after establishing a connection - and discard either the 400 or the 200 that should come back, them immediately execute the _intended_ command... Might be a useful trick to try? 

(BTW I can't get the code paster to honour the CRs, sorry, and I can't seem to find how to bake them in myself. What's the trick??).

**Comment by simonhac** [comment] 2017-05-01 11:19
@greiginsydney i haven't noticed the `400 Syntax Error.` before -- i'll keep an eye out for it. i'm certainly not getting it:
![image](https://cloud.githubusercontent.com/assets/20500649/25578600/ad04e728-2eb3-11e7-8aeb-04565d948732.png)

can you please paste in the same section from your console?

(my code doesn't have very clever error handling yet -- still to come.)

(to quote a block of text, use three back-quote chars. the ![image](https://cloud.githubusercontent.com/assets/20500649/25578527/f3e2f92e-2eb2-11e7-9529-3bebb8169af7.png) button does it automagically _iff_ you have multiple lines selected.)

**Comment by greiginsydney** [comment] 2017-05-01 11:30
Ahhh, Paste first THEN format. Doh.

```
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:

    ââââââââââââââ
    â 031-45-154 â
    ââââââââââââââ

  cbus:client sent command '[100] dbgetxml //19P' +474ms
[5/1/2017, 11:28:20 AM] Homebridge is running on port 51826.
  cbus:client rx snippet 343 'Begin XML snippet' +663ms
  cbus:client rx snippet 347 '<?xml version="1.0" encoding="utf-8"?>' +5ms
  cbus:client rx snippet 347 '<Installation><OID>24f1a3b0-1087-1035-8cb1-f8adf55e0923</OID><DBVersion>2.3</DBVersion><Version>1.0â¦' +41ms
  cbus:client rx response { commandId: 100, code: 344, matched: false, processed: false, type: 'response', raw: '[100] 344 End XML snippet' } +39ms
  cbus:client matched request '[100] dbgetxml //19P' with response '[100] 344 End XML snippet' (0 pending requests) +8ms
homebridge@raspberrypi:~$

```

**Comment by greiginsydney** [comment] 2017-05-01 11:55
My friend the Syntax error is back straight after the reboot:

```
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
[30m[47m                       [49m[39m
[30m[47m    ┌────────────┐     [49m[39m
[30m[47m    │ 031-45-154 │     [49m[39m
[30m[47m    └────────────┘     [49m[39m
[30m[47m                       [49m[39m
  [35;1mcbus:client [0msent command '[32m[1m[100] dbgetxml //19P[22m[39m' [35m+280ms[0m
[37m[5/1/2017, 11:39:32 AM][39m Homebridge is running on port 51826.
  [35;1mcbus:client [0m[34mrx response { commandId: 100, code: 400, matched: false, processed: false, type: 'response', raw: '[100] 400 Syntax Error.' }[39m [35m+69ms[0m
  [35;1mcbus:client [0mmatched request '[35m[4m[100] dbgetxml //19P[24m[39m' with response '[35m[4m[100] 400 Syntax Error.[24m[39m' [2m(0 pending requests)[22m [35m+5ms[0m
  [35;1mcbus:client [0m[31mrx unparsable line: '[100] 400 Syntax Error.', error: TypeError: Cannot read property 'content' of undefined
  [35;1mcbus:client [0m    at Object.client.getDB.result [as callback] (/usr/lib/node_modules/homebridge-cbus/lib/cgate-database.js:65:31)
  [35;1mcbus:client [0m    at CBusClient._resolveResponse (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:587:12)
  [35;1mcbus:client [0m    at CBusClient._socketReceivedLine (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:628:10)
  [35;1mcbus:client [0m    at Carrier.<anonymous> (/usr/lib/node_modules/homebridge-cbus/lib/cgate-client.js:175:9)
  [35;1mcbus:client [0m    at emitOne (events.js:96:13)
  [35;1mcbus:client [0m    at Carrier.emit (events.js:191:7)
  [35;1mcbus:client [0m    at /usr/lib/node_modules/homebridge-cbus/node_modules/carrier/lib/carrier.js:24:12
  [35;1mcbus:client [0m    at _combinedTickCallback (internal/process/next_tick.js:73:7)
  [35;1mcbus:client [0m    at process._tickCallback (internal/process/next_tick.js:104:9)[39m [35m+4ms[0m
  [35;1mcbus:client [0m[34mrx event { time: '20170501-114026', code: 800, processed: false, message: 'cgate - C-Gate started.', type: 'event', raw: '#e# 20170501-114026 800 cgate - C-Gate started.' }[39m [35m+53s[0m
  [35;1mcbus:client [0m[34mrx event { time: '20170501-114026', code: 807, processed: false, message: 'cgate - Logback logging active.  Destination=\'logs/event.txt\'. Size=5000000 bytes. History=7 days. Asynchronous=yes.', type: 'event', raw: '#e# 20170501-114026 807 cgate - Logback logging active.  Destination=\'logs/event.txt\'. Size=5000000 bytes. History=7 days. Asynchronous=yes.' }[39m [35m+8ms[0m
  [35;1mcbus:client [0m[34mrx event { time: '20170501-114030', code: 751, processed: false, message: '//19P - Tag information changed at tag address: //19P/Installation oldtag: null newtag: null', type: 'event', raw: '#e# 20170501-114030 751 //19P - Tag information changed at tag address: //19P/Installation oldtag: null newtag: null' }[39m [35m+4s[0m
  [35;1mcbus:platform [0mTag information changed. [35m+0ms[0m
```

**Comment by simonhac** [comment] 2017-05-01 12:11
@greiginsydney that syntax error is very odd -- are you running `v2.10.6 (build 3145)` of C-Gate?

```
$ telnet 10.0.1.241 20023
Trying 10.0.1.241...
Connected to 10.0.1.241.
Escape character is '^]'.
201 Service ready: Clipsal C-Gate Version: v2.10.6 (build 3145) #cmd-syntax=1.0
```

**Comment by greiginsydney** [comment] 2017-05-01 21:40
Absolutely - that's the latest. FYI it's the ZIP installer version from this page:
http://www2.clipsal.com/cis/technical/downloads/c-gate

**Comment by simonhac** [comment] 2017-05-02 07:16
@greiginsydney i'm reticent to add a special retry mechanism unless this is reproducible.

is the syntax error on the first message of every session, or first message after C-Gate startup?

can you reproduce it by telnetting in to port 20023?

**Comment by simonhac** [comment] 2017-05-02 12:38
anyone else having this problem? (@anthonywebb?)

**Comment by anthonywebb** [comment] 2017-05-02 15:03
I have not seen anything like this yet.  I assume you have CGate running on windows?  Odd that there are some special characters in there?

**Comment by greiginsydney** [comment] 2017-05-02 20:33
Hi @anthonywebb , no my whole setup is self-contained on a Pi. The non-printing characters were probably due to inappropriate logging settings in Putty ("all session output" vs "printable output") - I think they're safe to disregard. (Sorry).

@simonhac I haven't been able to dupe the 400 SYNTAX ERROR by Telnetting to the C-Gate on 20023. If this doesn't show as a consistent issue, just bear in mind that *if* C-Gate hits you with a 400 as the first response in a session, just re-try your command.

**Comment by simonhac** [comment] 2017-05-03 02:01
@greiginsydney i'd like to be able to reproducible this issue before cutting code to address it.

**Comment by greiginsydney** [comment] 2017-05-05 21:22
@simonhac No disagreement there.

**Comment by simonhac** [comment] 2017-05-09 05:30
@greiginsydney please close this if you agree that the original issue has been addressed.

if/when you encounter the dreaded syntax error please open a new issue -- especially if it is reproducible!

**Comment by simonhac** [comment] 2017-05-15 03:27
assuming that this is closed. @greiginsydney, reopen if necessary.

**Closed by simonhac** 2017-05-15 03:27 UTC
